spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wjyefsvmap?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  bboss:
    elasticsearch:
      rest:
        hostNames: 127.0.0.1:9200

wjy:
  database:
    name: wjyefsvmap