server:
  port: 10001

zzn:
  netty:
    port: 10002


mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netty_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  elasticsearch:
    bboss:
      elasticsearch:
        rest:
          hostNames: localhost:9200
  redis:
    host: 10.82.183.134
    port: 6379
    password: 123456


coupon:
  user:
    name: zhangzin
    age: 19