spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wjyefsvmap?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
#  bboss:
#    elasticsearch:
#      rest:
#        hostNames: 192.168.3.159:9200
#  elasticsearch:
#    bboss:
#      elasticsearch:
#        rest:
#          hostNames: 192.168.3.159:9200,192.168.3.10:9200



wjy:
  database:
    name: wjyefsvmap
  jobId: 4