server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://119.3.167.123:3307/efsvmap?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: FT!lyxbj0829
#  elasticsearch:
#    bboss:
#      elasticsearch:
#        rest:
#          hostNames: 192.168.3.159:9200,192.168.3.10:9200


wjy:
  database:
    name: efsvmap
  jobId: 4